### ISSUE TITLE
Can't determine reason for network failure

### ISSUE THREAD

**Issue by loosebazooka** [cloudfoundry/openjdk-cnb#10]
```
[builder] 
[builder] Cloud Foundry OpenJDK Buildpack 1.0.0-M9
[builder]   OpenJDK JDK 11.0.3: Contributing to layer
[builder]     Downloading from https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz
[builder] Get https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%!B(MISSING)7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz: dial tcp: lookup github.com on 8.8.4.4:53: read udp 192.168.9.2:55208->8.8.4.4:53: i/o timeout
[builder] Error: failed to build: exit status 103

ERROR: failed with status code: 7
```

I don't know if this is the right place to post this, but there are a couple issues here.
1. I can't figure out why this network issue is happening - `wget` on the same adoptopenjdk address succeeds (my main issue)
2. The error message seems to not be escaping special chars in the string before printing `%2B7` -> `%!B(MISSING)7` (minor)

**Comment by loosebazooka** [comment]
Perhaps this issue belongs in the core project?

**Comment by nebhale** [comment]
Github's CDN has definitely been having problems the last couple of days (during my releases yesterday I had all sorts of download problems).  I'm not sure there's anything much that I can do to either improve reliability or diagnostics as [we use the Go HTTP API directly](https://github.com/cloudfoundry/libcfbuildpack/blob/master/layers/download_layer.go#L94-L116).

As far as the logging, that was [fixed](https://github.com/cloudfoundry/libcfbuildpack/commit/a502d170054268b55e2a960acb8749d4ca2e61bf#diff-1b6d76fc4dce2a06baf1d69be13d344aR77) some time ago and is in releases of the buildpacks later than M9.  We're working on a new release for the `cloudfoundry/cnb:bionic` builder and expect to have the `RC02` series of Java Buildpacks released today.

**Comment by nebhale** [comment]
Ah, you're concern was about the error message.  That error message again, comes from within the Go HTTP API, so I don't have any control over it.  We had the same problem in our logging and fixed it in the commit mentioned earlier, and they've clearly missed the same case we did.

**Comment by loosebazooka** [comment]
Ah thanks @nebhale, seems like maybe there are no actions on your side? Should we close this and refile the logging issue with libcfbuildpack?

**Comment by nebhale** [comment]
Yep.  It's in the logging bit of `libcfbuildpack` and I'm not sure how to really solve it yet 😐
